### PR TITLE
AO3-5684 AO3-6524 Use more precise selectors for JavaScript

### PR DESCRIPTION
**Pull request by sarken**
## Issue

https://otwarchive.atlassian.net/browse/AO3-5684
https://otwarchive.atlassian.net/browse/AO3-6524

## Purpose

Update some of the JavaScript to make sure we aren't applying it in places we shouldn't.

## Testing Instructions

Refer to Jira

### CODE REVIEW

**Comment by redsummernight** [comment]
There's one more jshint warning but this looks good.

**Review by redsummernight — APPROVED** [review]

**Comment by tickinginstant** [comment]
There are a bunch more, if you're trying to prevent side effects and not just patch the two most critical ones:
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L74
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L100
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L115
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L124
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L132
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L146
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L166
This one is particularly bad for reasons that I won't get into atm but which you can probably guess:
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L415
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L427
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/filters.js#L11
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/filters.js#L62
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/filters.js#L63
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/bootstrap/bootstrap-dropdown.js#L177

Some of these are non-functional without the right attributes, but they still call `event.preventDefault()`, which would block links with those classes from working.

There are also some not listed here that have behavior that won't be noticed in 99.9% of cases (e.g. adding `role="menu-item"` or adding an extra class to everything with a particular class). I didn't link them because this list is already long enough. It's also possible I missed some, because there are a lot of things to check.

(This is why I'm team change the CSS class names and/or use `data-*` selectors, btw, because adding those extra three lines everywhere is a mess.)

**Comment by sarken** [comment]
Yeah, no, we're not aiming to get all of them right now, just some that can be fixed quickly and with high confidence we won't actually break things while we do more comprehensive rewriting. On May 8, 2023, at 11:38 AM, tickinginstant ***@***.***> wrote:﻿
There are a bunch more, if you're trying to prevent side effects and not just patch the two most critical ones:
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L74
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L100
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L115
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L124
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L132
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L146
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L166
This one is particularly bad for reasons that I won't get into atm but which you can probably guess:
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L415
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/application.js#L427
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/filters.js#L11
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/filters.js#L62
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/filters.js#L63
https://github.com/otwcode/otwarchive/blob/4e1a23efe1f0ea792047c5405d91c9bc06d77c85/public/javascripts/bootstrap/bootstrap-dropdown.js#L177
Some of these are non-functional without the right attributes, but they still call event.preventDefault(), which would block links with those classes from working.
There are also some not listed here that have behavior that won't be noticed in 99.9% of cases (e.g. adding role="menu-item" or adding an extra class to everything with a particular class). I didn't link them because this list is already long enough. It's also possible I missed some, because there are a lot of things to check.
(This is why I'm team change the CSS class names and/or use data-* selectors, btw, because adding those extra three lines everywhere is a mess.)

**Comment by sarken** [comment]
How do we want to test `prepareDeleteLinks()`, so I know what to put in the testing instructions? It now relies on the `href` as well as `data-confirm`, which I believe I have confirmed _is_ on every `/confirm_delete` link and the `/confirm_purge` link, despite there originally being a fallback confirmation message in the JavaScript.

But do we want to take my word for it or test all the `confirm_delete_[whatever]_path` links? Testing all of the links would look like:

```
# create a collection with a gift exchange
## sign-up for the exchange and then on Sign-ups page, Delete Sign-up, make sure message warns all prompts will be lost
## sign-up for exchange again (you'll need two sign-ups) and run matching and send assignments, and then on Sign-ups page, Delete Sign-up, make sure message says potential matches need to be regenerated
## on Assignments page, use Purge Assignments
## on Challenge Settings, use Delete Challenge
## on Collection Settings, use Delete Collection
# create another collection
## from the Profile, Delete Collection
# create a tag set that is accepting nominations
## nominate some tags and Delete
## Delete the tag set
# create a draft work and from your Drafts page, Delete Draft
# post a work in a series
## from your Series page, access the series and Delete Series
## return to the work, and from its Edit Work page, Delete Work
# bookmark a work and from your Bookmarks page, Delete
# create a New Site Skin, and Delete from either the skins page or the bottom of the page shown after saving
# as any admin, create a New FAQ Category, return to admin FAQ index, and Delete
# as any admin, create New Wrangling Guideline, return to admin Wrangling Guidelines index, and Delete
# as superadmin, comms, support, or board admin, create a New Banner, return to Banners index, and Delete
```

I don't really think it's necessary to do all of that because the worst case is deleting will still work, but without JavaScript. (The exception is Wrangling Guidelines, which cannot be deleted without JavaScript due to [AO3-4974](https://otwarchive.atlassian.net/browse/AO3-4974). We need to test deletion there no matter what.)

**Comment by tickinginstant** [comment]
> Yeah, no, we're not aiming to get all of them right now, just some that can be fixed quickly and with high confidence we won't actually break things while we do more comprehensive rewriting.

Oh, I figured that since you were changing a bunch of non-critical things (`.toggled`, `#work-form`, `.expandable`) that you wanted to handle all of the code with visible side effects.

> But do we want to take my word for it or test all the `confirm_delete_[whatever]_path` links?

Probably good to test everything. This issue is critical enough that I'd be on board with reverting all issues in the current release to try to rush this to production, in which case I'd be fine skipping some testing steps. But since you're not doing that, and there are apparently a couple of BOT issues in the current release, you might as well be thorough — this is unlikely to be the thing holding up the release.

**Comment by sarken** [comment]
Since there weren't any protests to testing all the things, I have added them to the instructions!

**Review by redsummernight — APPROVED** [review]

**Pull request merged**
