### PR TITLE
AO3-6376 Remove "User" from username, password and email change page titles

### PR DESCRIPTION
**Pull request by phthallo**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6376

## Purpose

This PR adds conditional rendering of the singularised `controller_name` (User) based on whether the `controller.action_name` has 'change' in it (as in *change*_password, *change*_email etc.).

## Testing Instructions

Follow the instructions in the description of the Jira ticket. 

## References

N/A

## Credit

phthallo [Annabel Quach] (they/them)

### CODE REVIEW

**Comment by brianjaustin** [comment]
Hi Annabel,

Thank you for the contribution! Someone will be along to review it soon.

In the meantime, I've assigned the Jira issue to you and set its status to In Review, so no one will mistakenly create a duplicate pull request. I've also given your account permission to comment on, assign, and transition issues in the future.

Thanks again for the PR! If you have any questions, please feel free to contact our dev team at [otw-coders@transformativeworks.org](mailto:otw-coders@transformativeworks.org).

**Review by brianjaustin — CHANGES_REQUESTED** [review]
Thanks again for the PR! Because `application.html.erb` changes can have global impact, I'd like to avoid changing where we can to avoid unexpected impacts. However, we can use `@page_title` to override an action's default title (for example https://github.com/otwcode/otwarchive/pull/4675).

It looks like there's an implicit `change_password` action (similar for the other 2), so you would need to add an explicit method to https://github.com/otwcode/otwarchive/blob/c09729dbe28774f8c99856ad81665481c17db044/app/controllers/users_controller.rb
```rb
def change_password
  @page_title = t(".browser_title")
```
and since we try to extract translatable text where possible, the above also needs this to be added to https://github.com/otwcode/otwarchive/blob/f9da02285e2e18d9fe722c860104a930a5488ed5/config/locales/views/en.yml
```
# other keys
users:
  change_password:
    browser_title: Change Password
```

Please feel free to let me know if that raises any questions!

**Comment by phthallo** [comment]
Made some changes - I did use `page_subtitle` instead of `page_title` to keep the `| {app_name}` at the end of the tab name consistent with the other edit pages.

**Review by brianjaustin — APPROVED** [review]
Thank you!

**Pull request merged**
