### PR TITLE
I'm very sorry, but I don't know how to reach our end. I found this way

### PR DESCRIPTION
**Pull request by xnx3**
Hello, I am an open source project https://github.com/xnx3/translate Author Guan Leiming, first of all, it is an honor for our multilingual switching project to be recognized by your website https://1.ao3-cn.top/ We are also very pleased to be recognized by your website and provide convenience to more friends.

Your website is very popular and the traffic is also very high, which has caused a lot of pressure for our backend translation server. However, due to the fact that the server used in this project was purchased by me and has always been used for free without any source of income, there is a bit of pressure on me to invest in the server. Therefore, after multiple considerations, I still raised this issue with me, and I feel very ashamed.

There are several ways to negotiate with you:

Method 1: I wonder if you can share with me the cost of a translation server, such as $5 for every 1GB of translation traffic and calculations generated. According to our current statistics, your website can generate approximately 806884 translations per day, with a word count of 1555051713 characters, which translates to approximately 1.5G of traffic. With your sharing, it will greatly reduce the pressure on our server expenses. We will provide better services and maintenance for us.

Method 2: Your company will provide a server, such as in Singapore or the United States, and we will help us install the translation backend service for free for use.

Method 3: Your company will contribute a server to run the translation backend service, which can be used by us and also publicly shared with other friends

Method 4: Can you place an advertisement for us on a webpage in another language? We can generate some advertising fees to maintain server investment. For example, if our normal website is in English, if the other party is browsing the website in a non Chinese way, such as browsing in Chinese, we will display an advertisement for us

The above is just the way I can personally think of it. If you have a better idea, please let me know and I feel very guilty about sending you this question. However, life has forced me. My email is guanleiming@zvo.cn You can send me an email

I'm very sorry, but I don't know how to reach our end. I found this way

### CODE REVIEW

**Comment by EchoEkhi** [comment]
For future reference, the contact email address is [otw-coders@transformativeworks.org](mailto:otw-coders@transformativeworks.org).

**Comment by xnx3** [comment]
收到，原来如此，感谢感谢，还是中文舒坦

**Comment by sarken** [comment]
您好，@xnx3！
感谢联系我们。很不幸，正如 EchoEkhi 所说，https://1.ao3-cn.top/ 是一个代理网站，并非由OTW再创作组织所有。我们不知道该网站的所有者是谁。如果你能找到的话该站站长，不妨与他们取得联系。
如果对OTW再创作组织还有其他疑问，您可以继续使用 [transformativeworks.org](http://transformativeworks.org/) 上的表格，我们会通过电子邮件回复。(我们收到了你最初的信息，但有时我们需要几天时间才能回复）。

-

Hi, @xnx3!

Thanks for contacting us. However, as EchoEkhi said, https://1.ao3-cn.top/ is a proxy site and does not belong to the Organization for Transformative Works. We do not know who owns it, but if you can find out, you may want to get in touch with them.

If you have any more questions for the Organization for Transformative Works, you can continue to use the form at [transformativeworks.org](http://transformativeworks.org/) and we'll respond over email. (We did receive your initial message, but it sometimes takes us a few days to reply.)

**Comment by sarken** [comment]
I should also note that proxy sites are very important to fans who would otherwise be unable to access the Archive. While we always recommend caution when using a proxy, we do not officially condemn or endorse any particular proxy.

**Pull request closed without merging**
