### PR TITLE
AO3-4364 - Add Before and After task to disable/enable caching

### PR DESCRIPTION
**Pull request by ariana-paris**
Codeship is still flaky, Travis mildly better. Worth a shot, I guess.

### CODE REVIEW

**Comment by shalott** [comment]
Running travis again now to see if it consistently runs clean

**Comment by scottsds** [comment]
Failed on: ``` features/comments_and_kudos/comment_moderation.feature:66:in `Then I should see "Edited unfail comment"'```

**Comment by shalott** [comment]
The comment moderation is the new test added which doesn't have caching disabled, so that's not a bad sign since the rest passed. Have started travis running again for another go!

**Comment by shalott** [comment]
Passed clean, running again (at 8:41pm)

**Comment by sarken** [comment]
Failed on: `cucumber features/collections/collection_navigation.feature:4 # Scenario: Create a collection and check the links`

Running again, 9:56 AM UTC

**Comment by ariana-paris** [comment]
Have disabled caching on `comment_moderation.feature:54` and `collection_navigation.feature:4`. I have a nasty feeling the latter continued to flicker while I was testing things in my own repo, but we'll see what Travis makes of it...

**Pull request merged**
