### PR TITLE
AO3-4554 Change links in tos and tos_faq

### PR DESCRIPTION
**Pull request by zz9pzza**
https://otwarchive.atlassian.net/browse/AO3-4554

### CODE REVIEW

**Comment by sarken** [comment]
This looks good! However, I noticed that all the new links are http://www.transformativeworks.org, and we still have some old links that point to http://transformativeworks.org. Should we add the www to the old links as long as we're here?

**Comment by zz9pzza** [comment]
Should I open a pull request up for the following files which have "http://transformativeworks.org" for the new paths ?

app/views/external_authors/claim.html.erb
app/views/home/_intro_module.html.erb
app/views/home/about.html.erb
app/views/home/donate.html.erb
app/views/home/site_map.html.erb
app/views/layouts/_footer.html.erb
app/views/user_mailer/claim_notification.html.erb
app/views/user_mailer/claim_notification.text.erb
app/views/user_mailer/invitation_to_claim.html.erb
app/views/user_mailer/invitation_to_claim.text.erb

**Comment by sarken** [comment]
If that's something we should change, yes, please! It will need an issue, too.

**Comment by sarken** [comment]
Marking ready to merge -- the test failures are unrelated.

**Pull request merged**
