### PR TITLE
AO3-4385 Update session handling

### PR DESCRIPTION
**Pull request by zz9pzza**
https://otwarchive.atlassian.net/browse/AO3-4385

Use ssl for session operations.

This doesn't get run in development or in test. 

Check that you can log in as a user and as an admin.

Check that when you look at the source it has a https url.

### CODE REVIEW

**Comment by cesy** [comment]
Looks logical, but will need a senior coder/systems knowledge to review as it's the kind of dangerously simple thing that has a big effect. Since it only excludes test, it will run on staging so can be checked with a manual test on Test Archive.

**Comment by zz9pzza** [comment]
The problem with review is the number of spare senior coders/systems people is low, @elzj ?

**Comment by shalott** [comment]
Yeah, my concern is that because it excludes test, automated testing gives us nothing, and worse than that, it means that we're introducing a massive discrepancy between our test and production environments going forward. Is there any way to make this work WITHOUT excluding the test environment?

**Comment by zz9pzza** [comment]
So I can get https working well in staging, I can't get this working in our automated tests, sorry ( unless you have any ideas )

**Comment by shalott** [comment]
I poked around and found this, might work? 

https://github.com/pat/thin-glazed

**Comment by zz9pzza** [comment]
I am less than convinced that putting this in to test is a good idea.

**Comment by shalott** [comment]
OK, let's try it on staging (ideally on its own with nothing else merged) and see how it behaves. 

One other question: do we have any absolute URLs being generated anywhere in the app still or have they all been cleaned up and turned into relative?

**Comment by zz9pzza** [comment]
My truthful answer is I am not sure, given that this is preparation for moving to an all https front end and that will go via a testing url before we move to it being the default for https always then it is really low risk I believe.

**Comment by zz9pzza** [comment]
So this should just effect both user and admin logins.

( However I have a cold right now and my certainty is not as high as I would like ).

**Pull request merged**
