### PR TITLE
AO3-5255 Allow tag set descriptions to be summary length

### PR DESCRIPTION
**Pull request by sarken**
## Issue

https://otwarchive.atlassian.net/browse/AO3-5255

## Purpose

Allows tag set descriptions to be the length we use for summaries (as defined in the updated config file in #3180). The field is now a textarea labeled "Description" with a character counter beneath it.

## Testing

Refer to JIRA

## References

Includes #3180 -- actual relevant commits are a333afe and e074a4c.

You can see the validation is already set up to be summary length and this is just a front end issue here: 

https://github.com/otwcode/otwarchive/blob/8033d2edb3a6fde89e81021b9bfb71f5be61c16d/app/models/tagset_models/owned_tag_set.rb#L48-L51

### CODE REVIEW

**Comment by sarken** [comment]
Marking Needs Coder Action due to merge conflicts.

**Comment by redsummernight** [comment]
Still good. **Note to ourselves to merge #3180 before this one**.

**Comment by sarken** [comment]
Resolved merge conflicts.

**Comment by sarken** [comment]
Closing, will reopen at the same time I reopen #3180

**Pull request closed without merging**
