### PR TITLE
AO3-6308 User suspension message provides incorrect time for the end of a user's suspension

### PR DESCRIPTION
**Pull request by Cesium-Ice**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6308  

## Purpose

What does this PR do?
Fix incorrect time for the end of a user's suspension

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?

If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions instead.

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?

Cesium-Ice, she/her
If you have a Jira account, please include the same name in the "Full name"
field on your Jira profile, so we can assign you the issues you're working on.

*Please note that if you do not fill in this section, we will use your GitHub account name and
they/them pronouns.*

### CODE REVIEW

**Comment by Cesium-Ice** [comment]
The test failures appear related to external works, which I did not change, so I'm not sure why that's happening

**Comment by sarken** [comment]
I am pretty sure the test failures are related to Dreamwidth moving away from Cloudflare. They just [tweeted](https://twitter.com/dreamwidth/status/1566714180018774017) some people are having trouble accessing the site while they tweak their DDoS protection.

**Comment by Cesium-Ice** [comment]
Hmm, would this be fixed by restarting the tests, then?

**Comment by sarken** [comment]
No, but I just merged #4331, which moves us away from using Dreamwidth in our tests. If you update your branch with master, that should fix it!

**Pull request closed without merging**
