### PR TITLE
AO3-3719 Return to the restricted work after login

### PR DESCRIPTION
**Pull request by zz9pzza**
This makes it more explicit in the code I hope, the login url will look like 

http://ao3.org/login?restricted=true&return_to_url=%2Fworks%2F17

https://otwarchive.atlassian.net/browse/AO3-3719

### CODE REVIEW

**Comment by sarken** [comment]
Assigning this to @elzj because I vaguely remember her having thoughts on this.

**Comment by shalott** [comment]
Is there an issue and a test that covers this already? I'm not clear on what is broken here and why this is better practice than what is currently happening -- is this a new best practice?

**Comment by zz9pzza** [comment]
So I have added a link to the issue ( https://otwarchive.atlassian.net/browse/AO3-3719 ) 

I can try and write a test if that would help ?

**Comment by shalott** [comment]
Yes please on a test! Ideally a test that breaks for master first and that this pullreq then fixes? :D

**Comment by zz9pzza** [comment]
I have written a test which I will put in a separate pull request however unfortunately it works in test.... ( well locally at least. )

https://github.com/otwcode/otwarchive/pull/2437

**Comment by shalott** [comment]
Commenting here to add we need to know why this is working & passing in test (and dev?) and get it to fail properly before we use the fix IMO.

**Comment by zz9pzza** [comment]
Even if we don't understand why the old code doesn't work, but we do understand why the new code would, isn't that an improvement.

( My intuition is pointing towards the fact that beta has so much more traffic and servers.... )

**Comment by redsummernight** [comment]
The issue cannot be reproduced in 2019/07, so we're closing this for now.

**Pull request closed without merging**
