### PR TITLE
AO3-4509 Add gem security to tests

### PR DESCRIPTION
**Pull request by zz9pzza**
https://otwarchive.atlassian.net/browse/AO3-4509
So we will either need to update a gem or add it to an exceptions list

### CODE REVIEW

**Comment by cesy** [comment]
Can we add some commentary about the ones we've chosen to ignore and why, please? Either in the code or in the comments in Jira, just somewhere that people can trace back if necessary. This looks like a good check in principle, though.

**Comment by zz9pzza** [comment]
They are the ones which we fail on right now, so if we didn't ignore them then the tests would fail.

https://github.com/otwcode/otwarchive/pull/2322
https://github.com/otwcode/otwarchive/pull/2319

Are the ones I think

**Comment by cesy** [comment]
Great, so if we merge this first, we can take them out after those two PRs get merged, or if we merge this last, we can take them all out. Neat! Seems good to go, then. It's small enough it's not a significant performance hit on Travis or anything.

**Comment by zz9pzza** [comment]
Yes

**Comment by shalott** [comment]
Looks good to me as well

**Pull request merged**
