### PR TITLE
AO3-5989 Correct broken link on skins help text

### PR DESCRIPTION
**Pull request by designateddolt**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-5989

## Purpose

What does this PR do?
Fixed broken link as per jira issue

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?
Check that it goes to a working link :)

If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions instead.

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)? salt, they/them

If you have a Jira account, please include the same name in the "Full name"
field on your Jira profile, so we can assign you the issues you're working on.

*Please note that if you do not fill in this section, we will use your GitHub account name and
they/them pronouns.*

### CODE REVIEW

**Review by sarken — CHANGES_REQUESTED** [review]
The changes look good to me, but it looks like there's a merge conflict. Would you like to resolve it? If not, one of us can.

**Comment by designateddolt** [comment]
> The changes look good to me, but it looks like there's a merge conflict. Would you like to resolve it? If not, one of us can.

I'm not sure what to do to resolve it so I think it's probably best if someone else does?

**Comment by sarken** [comment]
Sure, I can resolve them for you!

In general, the easiest way to deal with merge conflicts is to avoid them in the first place. 😆 So when I need to submit additional changes for an issue that's marked Broken on Test, I like to start with a fresh branch that's up to date with upstream master:

```
git checkout master
git pull upstream master
git push origin master
# Delete the old branch.
git branch -D AO3-5989
git push origin :AO3-5989
# Create a new branch with the same name; 
# you can also skip the previous commands and use a new name
# e.g., AO3-5989_BOT 
git checkout -b AO3-5989
```

Buuut if you have a pull request open and a reviewer tells you it has merge conflicts that need to be resolved, the process is a bit different:

```
git checkout master
git pull upstream master
git push origin master
# Now incorporate the changes from master into your branch.
git checkout AO3-5989
git merge master
```

That's where Git is going to yell about conflicts:

```
Auto-merging public/help/skins-creating.html
CONFLICT (content): Merge conflict in public/help/skins-creating.html
Removing lib/tasks/invitations.rake
Removing features/support/factories.rb
Removing app/views/tag_wranglings/discuss.html.erb
Removing app/views/invite_requests/new.html.erb
Removing app/views/invite_requests/edit.html.erb
Removing app/sweepers/kudos_sweeper.rb
Automatic merge failed; fix conflicts and then commit the result.
```

So now is when you open up the offending file (`public/help/skins-creating.html`) in your code editor. (There may be multiple files with conflicts, or multiple conflicts within a single file.)

For this, you'd see a section that looks like this:

```
<<<<<<< HEAD
      <a href="https://www.w3schools.com/colors/colors_names.asp">the set of commonly-supported color names</a>.)
=======
      <a href="https://www.w3schools.com/css/css_colornames.asp">the set of commonly-supported color names</a>.)
>>>>>>> master
```

Here you have to decide what the correct code should be. Then you'd replace all five of those lines with the desired change:

```
      <a href="https://www.w3schools.com/colors/colors_names.asp">the set of commonly-supported color names</a>.)
```

Then you can save your changes and commit and push as usual to update your pull request:

```
git add public/help/skins-creating.html
git commit -m "AO3-5989 Merge with master"
git push origin AO3-5989
```

**Review by sarken — APPROVED** [review]

**Comment by designateddolt** [comment]
tysm! that's super helpful :) i'll try avoid them in future!

**Pull request merged**
