### PR TITLE
AO3-5759 Add Lockup to password protect staging

### PR DESCRIPTION
**Pull request by sarken**
## Issue

https://otwarchive.atlassian.net/browse/AO3-5759

## Purpose

Adds the [Lockup gem](https://lockupgem.com) for staging and allows us to set a password and password hint in config.yml. 

## Testing Instructions

Refer to Jira.

### CODE REVIEW

**Comment by zz9pzza** [comment]
The cookie set by Lockup defaults to 5 years.  ?

Is this too long ?

**Comment by sarken** [comment]
The cookie will expire whenever we change the code word, so I think five years is fine.

**Comment by derenrich** [comment]
you do realize this leaks the password in the source? I assume this is temporary or something?

**Comment by sarken** [comment]
Yes, we put temporary values in the repository and then change them in Ansible.

**Pull request merged**
