### PR TITLE
AO3-4564 upgrade to ruby 2.2.5

### PR DESCRIPTION
**Pull request by zz9pzza**
https://otwarchive.atlassian.net/browse/AO3-4564

### CODE REVIEW

**Comment by shalott** [comment]
Gone grey, I assume there's no point updating this until after we do the 2.1.9 upgrade and test

**Comment by shalott** [comment]
Tests failing on bundle install of raindrops -- incompatible?

**Comment by sarken** [comment]
Grey, although that is somewhat expected.

**Comment by shalott** [comment]
Since the Ruby 2.1.9 upgrade went fine I would suggest first merging (one at a time) the gem upgrades and then this. Marking it ready.

**Pull request merged**
