### PR TITLE
AO3-5737 Put border on right side for RTL blockquotes

### PR DESCRIPTION
**Pull request by palindromordnilap**
## Issue

https://otwarchive.atlassian.net/browse/AO3-5737

## Purpose

This PR moves the border and margin to the right for `blockquote` elements either with or inheriting the `dir="rtl"` attribute. The addition to the stylesheet is exactly the same as written in the Jira issue. Here is a comparison using [this news post](https://archiveofourown.org/admin_posts/13531) (with the HTML edited to add the `dir="rtl"` attribute to the blockquote):

Without the fix:

Screenshot_2020-01-27 ארכיון משלנו זכה בפרס הוגו לשנת 2019 עבור היצירה הקשורה הטובה ביותר Archive of Our Own

With the fix:

Screenshot_2020-01-27 ארכיון משלנו זכה בפרס הוגו לשנת 2019 עבור היצירה הקשורה הטובה ביותר Archive of Our Own(1)

## Testing Instructions

See testing instructions on the Jira ticket.

## References

[AO3-5735](https://otwarchive.atlassian.net/browse/AO3-5735), once done and deployed, should mean admin posts in a RTL language wouldn't have to be edited to add the `dir="rtl"` attribute to all blockquote elements.

## Credit

Alix R, she/her

### CODE REVIEW

**Comment by palindromordnilap** [comment]
Ah, I thought the nested blockquotes thing was handled by the existing CSS, but apparently, adding `[dir="rtl"]` makes it more specific than `.userstuff blockquote blockquote`. Going to fix all of that now, thank you!

**Comment by palindromordnilap** [comment]
I also just checked, and news/FAQ posts do have the `dir="rtl"` attribute set in `userstuff` -- well, news post will, once https://github.com/otwcode/otwarchive/pull/3743 is deployed.

**Comment by sarken** [comment]
Just a quick update so you know I'm not ignoring you! In light of the issues discovered in my first review, the development team is having a bit of a discussion about how involved we want this fix to be (i.e. are we going to try to cover every possible nesting scenario or just the most basic one). I should get back to you later this week.

In the meantime, thanks for working on this, and sorry it turned out not to be as straightforward as we'd hoped!

**Comment by palindromordnilap** [comment]
That does sound like something we should be using. I'll get right on it!

**Pull request merged**
