### PR TITLE
4193 Drafts show up on Collected Works page

### PR DESCRIPTION
**Pull request by scottsds**
Resolves issue: https://code.google.com/p/otwarchive/issues/detail?id=4193

### CODE REVIEW

**Comment by CristinaRO** [comment]
I'm also not sure about this, because the very specific original conditions make it look like it *was* meant to allow creators to check on drafts they meant to post to collections - say, someone misplacing a draft of their Yuletide story? >.>

**Comment by sarken** [comment]
Hmm. I'm thinking about this, and I know drafts for Yuletide-esque collections (anonymous, unmoderated) show up correctly in one's draft page -- I even checked just now. Maybe there's a problem with drafts in *moderated* collections disappearing unless `self.collected` is in there.

**Comment by sarken** [comment]
...nope. Drafts for moderated collections also appear on your Drafts page. (I just tried using my personal account to post a draft for testy's moderated collection. Sure enough, the draft appears on my Drafts page.)

**Comment by sarken** [comment]
@elzj Hi! We were thinking this would be a nice a pull request for the next deploy... do you happen to remember why the code was originally like this (that is, is there a reason we shouldn't merge this)?

**Comment by elzj** [comment]
This would actually cause drafts to show up in general search results where they'd get cached and shown to other people, so I'm closing to be on the safe side.

**Pull request closed without merging**
