### PR TITLE
AO3-4272 Prevent escaped HTML in listing of works "inspired by" Anonymous.

### PR DESCRIPTION
**Pull request by astirya**

### CODE REVIEW

**Comment by zz9pzza** [comment]
Can you add a link in future :)

https://otwarchive.atlassian.net/browse/AO3-4272

**Comment by ariana-paris** [comment]
While we're asking for ponies, could you also add a test that checks this is working as expected given various examples of HTML? (This can be either an Rspec or a Cucumber test depending on your preference - there will already be tests for bylines in there which you can take as inspiration)

**Comment by sarken** [comment]
Hi, astirya!

Will you be able to update this with the tests Ariana asked for? If not, please let us know and someone else can add them.

**Comment by sarken** [comment]
@redsummernight has been so kind as to pull this code and write the tests it needed, so I'm closing this in favor of #2894

**Pull request closed without merging**
