### PR TITLE
AO3-6384 Fix intermittent user_dashboard test failures

### PR DESCRIPTION
**Pull request by ceithir**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [ ] Have you added the [Jira](https://otwarchive.atlassian.net) issue number as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open?

## Issue

https://otwarchive.atlassian.net/browse/AO3-6384

## Purpose

The scenario "The user dashboard should list up to five of the user's works" of file `features/user/user_dashboard.feature` fails intermittently due to the works not necessarily always being created/indexed in the same order.
For example, "Work 2" can end up "older" than "Oldest Work", and thus the test fails because it expects "Oldest Work" to be out due to being too old.
This is an attempt at fixing that.

## Testing Instructions

Run `docker-compose exec -e RAILS_ENV=test web bundle exec cucumber features/users/user_dashboard.feature:55` X times on master, and, for a value of X great enough, it should fail from time to time.
Do the same on this branch, and it should pass every time.
Note: Yes, it's quite possible the PR does nothing and this is just dumb luck. No idea how to formally prove this solves the issue.

## Credit

Ceithir (he/him)

### CODE REVIEW

**Review by redsummernight — COMMENTED** [review]
The test likely fails because works are posted too quickly in succession, they end up with the same timestamps with no tie-breaker (see [`Work.latest`](https://github.com/otwcode/otwarchive/blob/a34b948905135709bac5333cd935e22ff1b93d6e/app/controllers/works_controller.rb#L128)). So adding a delay or an extra check between each work is a reasonable fix.

Depending on your setup, running tests locally might not be fast enough to cause this kind of error. To make sure, you should run the tests X times on GitHub Actions instead.

What I've done in the past is make a copy of this branch, modify automated-tests.yml to be like:

```yml
name: Automated Tests
on:
  push:
    # run on any branch
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

# ...
      matrix:
        tests:
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
          - command: cucumber
            arguments: features/users/user_dashboard.feature
```
and [rerun the tests a bunch of times](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow).

**Comment by ceithir** [comment]
https://github.com/otwcode/otwarchive/actions/runs/2824719336

**Comment by tickinginstant** [comment]
I don't think this fixes the intermittent failure. It's actually flaky [in the latest test run for this PR](https://github.com/otwcode/otwarchive/runs/7744553376?check_suite_focus=true#step:14:32):
```
features/users/user_dashboard.feature
......................................................F---------    HTML screenshot: /home/runner/work/otwarchive/otwarchive/tmp/capybara/screenshot_2022-08-09-11-05-55.686.html
......................................................................................................................................... (99.53s)

(::) failed steps (::)

expected not to find text "Oldest Work" in "Main Content While we've done our best to make the core functionality of this site accessible without javascript, it will work better with it enabled. Please consider turning it on! Example Archive beta User Navigation Hi, meatloaf! My Dashboard My History My Preferences Post New Work Import Work Log Out Site Navigation Fandoms All Fandoms Uncategorized Fandoms Browse Works Bookmarks Tags Collections Search Works Bookmarks Tags People About About Us News FAQ Wrangling Guidelines Donate or Volunteer Search Works Work Search: tip: arthur merlin words>1000 sort:hits Choices Dashboard Profile Preferences Skins Pitch Works (5) Drafts (0) Series (0) Bookmarks (0) Collections (0) Catch Inbox (0) Statistics History Subscriptions Switch Sign-ups (0) Assignments (0) Claims (0) Related Works (0) Gifts (0) Hi! It looks like you've just logged into the Archive for the first time. Learn some tips and tricks or dismiss this message permanently. For more guidance on using the site, check out our FAQ! If you need technical support, you can contact us through our Support and Feedback form. If you experience harassment or have specific questions about the Terms of Service, you can contact our Policy & Abuse team. × meatloaf Post New Edit Works Invitations ﻿ Recent works Newest Work by meatloaf Fandoms: Stargate SG-1 Not Rated No Archive Warnings Apply Other Complete Work 09 Aug 2022 Tags No Archive Warnings ApplyScary tag Language: English Words: 6 Chapters: 1/1 Hits: 0 Author Actions Edit Edit Tags Work 5 by meatloaf Fandoms: Stargate SG-1 Not Rated No Archive Warnings Apply Other Complete Work 09 Aug 2022 Tags No Archive Warnings ApplyScary tag Language: English Words: 6 Chapters: 1/1 Hits: 0 Author Actions Edit Edit Tags Work 4 by meatloaf Fandoms: Stargate SG-1 Not Rated No Archive Warnings Apply Other Complete Work 09 Aug 2022 Tags No Archive Warnings ApplyScary tag Language: English Words: 6 Chapters: 1/1 Hits: 0 Author Actions Edit Edit Tags Work 3 by meatloaf Fandoms: Stargate SG-1 Not Rated No Archive Warnings Apply Other Complete Work 09 Aug 2022 Tags No Archive Warnings ApplyScary tag Language: English Words: 6 Chapters: 1/1 Hits: 0 Author Actions Edit Edit Tags Oldest Work by meatloaf Fandoms: Stargate SG-1 Not Rated No Archive Warnings Apply Other Complete Work 09 Aug 2022 Tags No Archive Warnings ApplyScary tag Language: English Words: 6 Chapters: 1/1 Hits: 0 Author Actions Edit Edit Tags Works (5) Footer About the Archive Site Map Diversity Statement Terms of Service DMCA Policy Contact Us Policy Questions & Abuse Reports Technical Support & Feedback Development Known Issues GPL by the OTW" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:196:in `block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:6:in `with_scope'
./features/step_definitions/web_steps.rb:194:in `/^(?:|I )should not see "([^"]*)"(?: within "([^"]*)")?$/'
features/users/user_dashboard.feature:69:in `And I should not see "Oldest Work"'
```
This test is "flaky" rather than "failed" because the cucumber tests are set to rerun once on failure, and it succeeded the second time. But it does suggest that you could probably get a real failure if you repeated the test enough.

It's possible that this improves the success rate, but I think this needs either some `sleep` calls or time travel to actually fix the issue. Or tiebreaking in the scope.

**Comment by redsummernight** [comment]
Time travel should work, yeah. You can try replacing the "should see" check  with "it is currently 1 second from now". We use it throughout the test suite; it's from [cucumber-timecop](https://gitlab.com/zedtux/cucumber-timecop/-/blob/master/lib/cucumber/timecop.rb).

**Comment by ceithir** [comment]
Oh, indeed, the previous "fix" appears to have been magical thinking to the max.

Time travel on the other hand seems to have done the trick: https://github.com/otwcode/otwarchive/actions/runs/2832213113

Thanks.

**Review by tickinginstant — APPROVED** [review]
Looks good!

**Pull request merged**
