### PR TITLE
AO3-6259 upgrade elasticsearch to 8.4.0

### PR DESCRIPTION
**Pull request by gmjimenezc**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6259

## Purpose
Upgrade elasticsearch to 8.4.X

What does this PR do?
* Updates image version to 8.4.1
* Updates gem version to 8.4.0

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?

If you have a Jira account with access, please update or comment on the issue
with any new or missing testing instructions instead.

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

What name and pronouns should we use to credit you in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?

warlockmel (she/her)

### CODE REVIEW

**Comment by gmjimenezc** [comment]
@redsummernight @sarken do you know what can possibly cause this? I haven't been able to run it locally due to the ruby version. Not sure if this update depends on something else too (I'm not used to working with ruby or gems completely so pardon me hehe)

**Comment by EchoEkhi** [comment]
It's probably because of elasticsearch-transport migrating to elastic-transport or something like that.

https://github.com/elastic/elasticsearch-ruby/issues/1344

If you want to run the project on your machine, try using the docker images! They don't conflict with your local ruby versions.

Guide here: https://github.com/otwcode/otwarchive/wiki/Docker

**Comment by EchoEkhi** [comment]
I think you missed line 222 perhaps?

**Comment by EchoEkhi** [comment]
I think you might need to change the `Elasticsearch::Transport`s to `Elastic::Transport`

**Comment by gmjimenezc** [comment]
Thanks, I noticed it too and already changed it @EchoEkhi.

**Review by redsummernight — APPROVED** [review]

**Comment by brianjaustin** [comment]
Hi @gmjimenezc,

Thank you so much for working on this! We're planning to release this next (https://otwarchive.atlassian.net/projects/AO3/versions/13093/tab/release-report-all-issues). Do you have time to take a look at the conflicts (and update Elasticsearch to the latest version, 8.14) in the next few days? If not (or if we don't hear anything by this weekend – the 29th/30th of June), no worries, we can take care of it!

Thanks again for your hard work!

**Comment by brianjaustin** [comment]
Closing in favor of #4867

**Pull request closed without merging**
