### PR TITLE
AO3-4411 iOS icons

### PR DESCRIPTION
**Pull request by cesy**
https://otwarchive.atlassian.net/browse/AO3-4411

As per Priscilla's request, getting rid of the old-style grey curve. I went for plain white as safe and neutral, but is it too blinding and would grey be better, or is this still enough of an improvement?

### CODE REVIEW

**Comment by sarken** [comment]
Just a few questions! 

- Is having some red-on-white and others white-on-red intentional? 
- Is it intentional that the logo is bigger on the red-on-white versions and smaller on the white-on-red?
- apple-touch-icon-144x144-precomposed.png and apple-touch-icon-precomposed.png are somewhat blurry compared to the previous versions -- is that because there's some sort of a file size restriction they have to fit in? 

If these are all desired, that's cool -- we should just note them on the issue so testers are aware, too.

**Comment by cesy** [comment]
All unintentional or laziness, now fixed. Are you happy with the string of commits or would you like me to squash them?

**Comment by sarken** [comment]
The commits are fine unsquashed -- we're not picky about that at all.

However, the precomposed ones still have some definite fuzziness in the logo that's not there with the square images. What program are you using, and what file type and image size are you starting with? Maybe we can figure out how to fix it.

(@bingeling, roping you in on this!)

**Comment by cesy** [comment]
Blurriness should now be fixed.

**Comment by sarken** [comment]
Looks good!

**Pull request merged**
