### PR TITLE
AO3-3847 Add delays to make series in work blurb tests less flaky

### PR DESCRIPTION
**Pull request by redsummernight**
## Issue

https://otwarchive.atlassian.net/browse/AO3-3847

## Purpose

Wait a few seconds for cache expiration to happen.

## Testing Instructions

Automated. I got `TEST_GROUP="cucumber -r features features/other_b"` to pass 10 times consecutively on my fork's Travis.

### CODE REVIEW

**Comment by redsummernight** [comment]
Typical... I just see this again on my fork:
```
expected to find text "Part 1 of Many a Robot" in "Recent works WALL-E by testuser1 Fandoms: Stargate SG-1 Not Rated No Archive Warnings Apply Other Complete Work less than 1 minute ago Tags No Archive Warnings ApplyScary tag Series Part 1 of Robots Language: English Words: 6 Chapters: 1/1 Hits: 0 Author Actions Edit Edit Tags" (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/web_steps.rb:139:in `block (2 levels) in <top (required)>'
./features/step_definitions/web_steps.rb:14:in `block in with_scope'
./features/step_definitions/web_steps.rb:14:in `with_scope'
./features/step_definitions/web_steps.rb:138:in `/^(?:|I )should see "([^"]*)"(?: within "([^"]*)")?$/'
/home/travis/.rvm/rubies/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/rubies/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
features/other_b/series.feature:156:in `Then I should see "Part 1 of Many a Robot" within "#user-works"'

Failing Scenarios:
cucumber features/other_b/series.feature:142 # Scenario: Rename a series
```
I think I need to space out the initial work creation and the edit, instead of waiting after the edit.

**Comment by sarken** [comment]
😭 

I'll set it to needs action, in that case!

**Comment by sarken** [comment]
It did indeed fail on the re-run here, too, btw.

**Comment by redsummernight** [comment]
Second time's the charm, other_b passed 15 times here: https://travis-ci.org/redsummernight/otwarchive/builds/638734313.

**Pull request merged**
