### PR TITLE
AO3-5845 Prevent Twitter share button from vanishing in Firefox and Chrome

### PR DESCRIPTION
**Pull request by derenrich**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added tests for any changed functionality?
* [ ] Have you added the [JIRA](https://otwarchive.atlassian.net) issue number as the *first* thing in your pull request title (eg: `AO3-1234 Fix thing`)
* [ ] Have you updated or commented on the JIRA issue with the information below?

## Issue

https://otwarchive.atlassian.net/browse/AO3-5845

## Purpose

Force the twitter share button to be visible. There are doubtlessly more elegant fixes but this works.

## Testing Instructions

Stage the changes. Click share. Note that the share button is visible.

## References

No.

## Credit

*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?*

derenrch

*What pronouns do you prefer (she/her, he/him, zie/hir etc)?*

he/him

### CODE REVIEW

**Comment by sarken** [comment]
I've looked into this and created an issue, but please refrain from submitting any more pull requests that do not already have corresponding Jira issues.

Jira issues are necessary to ensure our code reviewers and testers have the necessary information to evaluate changes. As the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md) note, bugs that are not in the issue tracker should be [submitted to Support](https://archiveofourown.org/support). Support will then work with our development team to verify the problem, agree on a desired solution, and document this information in an issue. (This can take some time, depending on the level of detail in the report, the nature of the problem, and the teams' current workloads and priorities.)

Future pull requests that do not have an issue are likely to be closed.

**Comment by derenrich** [comment]
yeah I tried to add the issue to jira first but your jira seems misconfigured and I couldn't submit an issue. i submitted it to your support link but I got no response.

**Comment by sarken** [comment]
Jira is set up so only approved OTW volunteers can make issues. This ensures issues have gone through the process described in my previous comment and contain all the necessary information. However, if you'd like permissions to claim and comment on existing issues, please let us know your Jira name and we'll update your settings.

I've checked on the status of your Support ticket and can confirm it was received a few minutes before this pull request was submitted. Our Support volunteers do reply to every ticket, but it will generally take several days -- sometimes longer, depending on the the complexity of the ticket, their current workload, and volunteers' availability (many Support volunteers are also students and have been busy with start-of-term commitments following the holidays).

**Comment by derenrich** [comment]
oh I see. yeah my jira account is https://otwarchive.atlassian.net/jira/people/5e233cc1a0120f0ca70e1d3b

is it common for open source projects to have locked down issue trackers?

**Comment by sarken** [comment]
Great, thanks! I've given you those permissions.

I can't speak to what other open source projects do with their issue trackers, but we've found it necessary to avoid spam, duplicate and incomplete issues, etc. I imagine it's not uncommon, given GitHub's option to disable a project's issue tracker. 

I happened to be checking the AO3_Status account on Twitter and noticed your tweet about reporting a security issue. As with any other bugs, the best way to get in touch is to contact Support with an overview of the issue and, depending on what it is, they'll either take your report or put you in touch with the person best suited to handling the issue.

**Comment by derenrich** [comment]
alright, thanks

**Pull request merged**
