### PR TITLE
AO3-5421 Adds line-height to userstuff list items

### PR DESCRIPTION
**Pull request by anechol**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

[https://otwarchive.atlassian.net/browse/AO3-5421](https://otwarchive.atlassian.net/jira/software/c/projects/AO3/issues/AO3-5421?)

## Purpose

Adds `line-height` to list item tags within `.userstuff` class.

## Testing Instructions

See Jira ticket

## Credit

anechol (she/her)

### CODE REVIEW

**Comment by sarken** [comment]
Hi, anechol!

Thank you so much for this pull request. Someone will be along to review it soon.

I've updated the Jira issue status to In Review, so no one will mistakenly create a duplicate pull request. If you'd like the ability to comment on, assign, and transition issues in the future, you're welcome to create a Jira account! You can just reply here with the account name and we'll set up the permissions for you. (It makes things a bit easier for us on the organizational side if the Full Name on your Jira account either closely matches the name you'd like us to credit in the release notes or includes it in parentheses, e.g. "Nickname (PREFERRED NAME).")

Thanks again for contributing! If you have any questions, you can contact us at otw-coders@transformativeworks.org.

**Review by sarken — CHANGES_REQUESTED** [review]
Thanks for looking into this!

I noticed this doesn't address the issue with text following block quotes, but when I tried to reproduce it using the steps outlined on Jira, the text was wrapped in paragraph tags 🎉   So that's probably not a huge issue going forward, although it will probably still be present in older works.

That being said, there's at least one other place this issue can occur: in `dt` tags. (I can update the issue to mention this and remove the block quote information.)

I'm wondering if, rather than trying to fix all the individual problem areas, it would make sense to apply the fix to `.userstuff` itself. I was a little leery that it might affect the various headings, which have their own line heights, but it doesn't seem to when I give it a quick try using my browser's dev tools. 

Do you think that would work without having major side effects?

**Comment by anechol** [comment]
> Thanks for looking into this!
> 
> I noticed this doesn't address the issue with text following block quotes, but when I tried to reproduce it using the steps outlined on Jira, the text was wrapped in paragraph tags 🎉 So that's probably not a huge issue going forward, although it will probably still be present in older works.
> 
> That being said, there's at least one other place this issue can occur: in `dt` tags. (I can update the issue to mention this and remove the block quote information.)
> 
> I'm wondering if, rather than trying to fix all the individual problem areas, it would make sense to apply the fix to `.userstuff` itself. I was a little leery that it might affect the various headings, which have their own line heights, but it doesn't seem to when I give it a quick try using my browser's dev tools.
> 
> Do you think that would work without having major side effects?

@sarken Thanks for clarifying all this. I think the easiest, albeit "riskier" solution is to just add the line-height to the `userstuff` class as you mentioned, and yeah, as far as I can tell in the browser, it doesn't seem to be affecting any of the headings. I've gone ahead and committed a change reflecting that. Let me know what you think or if there are any other tags to be mindful of.

**Review by sarken — APPROVED** [review]
This looks good to me now, both in terms of code and in terms of what I see in the browser -- thanks again! (And apologies for not getting back to you sooner; I was under the weather for a few weeks.)

**Pull request merged**
