### PR TITLE
AO3-4356 Make support languages editable by admins

### PR DESCRIPTION
**Pull request by elzj**
https://otwarchive.atlassian.net/browse/AO3-4356

### CODE REVIEW

**Comment by sarken** [comment]
Just wanted to say I'm pretty sure this is good, but it has some of my code, so it would be Right And Proper to have another set of eyes, too, when someone gets the change. (Also, I added the issue link to the description and the number to the title)

**Comment by scottsds** [comment]
This looks good to me.

**Comment by shalott** [comment]
Have reviewed, looks good, could use a test but ready to merge otherwise :)

**Comment by sarken** [comment]
Just leaving a note that the migration here is newer than the date in our updated schema file, so this is indeed good to merge.

**Pull request merged**
