### PR TITLE
Issue 4105 admin post in supported languages

### PR DESCRIPTION
**Pull request by zz9pzza**
Only use the languages which have a locale associated with them on the admin drop down list of languages

https://code.google.com/p/otwarchive/issues/detail?id=4105

### CODE REVIEW

**Comment by sarken** [comment]
I know this works -- I'm just not sure if there's a neater/better way to do it than putting something like `Language.where(id: Locale.all.map(&:language_id)).default_order` in a view file, so I'd like @elzj or @CristinaRO to weigh in before we mark this ready to merge.

**Comment by scottsds** [comment]
Perhaps something like what was done for the FAQ Rework Branch, where I made a helper to show only languages which have available translations: https://github.com/otwcode/otwarchive/pull/1013/files#diff-ca95a97690898776173fed6d792404d8R1

**Comment by zz9pzza** [comment]
I don't particularly like it as code, but the idea of shifting the identical code to a helper seems worse to me :(

**Comment by scottsds** [comment]
The idea is to try to avoid doing any data manipulation directly in the view, just an idea though.

**Comment by zz9pzza** [comment]
What I could do is do the calculation in the controller and use it in the view ?

**Pull request merged**
