### PR TITLE
AO3-4715 - Increase test coverage for challenges controller

### PR DESCRIPTION
**Pull request by scottsds**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added tests for any changed functionality?
* [x] Have you added the JIRA issue number as the *first* thing in your pull request title (eg: `AO3-1234 Fix thing`)
* [x] Have you updated the JIRA issue with the information below?

## Issue

https://otwarchive.atlassian.net/browse/AO3-4715

## Purpose

This add some test coverage to the challenges_controller.rb file. 

## Testing

Verify that code coverage has increased for the challenges_controller.rb file.

### CODE REVIEW

**Comment by scottsds** [comment]
@shalott maybe you have some ideas about the problem I'm having getting the last test in this suite to pass? I cannot figure out how to tell the challengescontroller what I want the @collection instance variable to be.

**Comment by zz9pzza** [comment]
Having a quick look at this the changes in "app/controllers/challenges_controller.rb" are formatting only ?

**Comment by zz9pzza** [comment]
I have looked though this and I can see what you are trying to do I think.

I think you would have to test one of the sub classes to get at load_challenge

However we already have 222 covering runs at that so I would take that bit out of the pull. The easiest way to look at coverage is to look at coveralls.io for example

https://coveralls.io/builds/8635223/source?filename=app%2Fcontrollers%2Fchallenges_controller.rb#L53

**Comment by scottsds** [comment]
@zz9pzza All I am able to see by following that coveralls link is:

Source Not Available

The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

**Pull request merged**
