### PR TITLE
AO3-6220 Update collection FAQ links in emails, TOS, and TOS FAQ

### PR DESCRIPTION
**Pull request by sharra44**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6220

## Purpose

Updates outdated FAQ references for the collections feature

## Testing Instructions

    Create a work

    Create a collection

    Add the work to the collection

    Change the collection status to 'unrevealed' or to 'anonymous' (or both)

    Follow the “Manage Items” link in the collection sidebar

    Follow the “Approved” link near the top of the page

    Check the “Anonymous” or “Unrevealed” (or both) boxes for the work you created

    Press “Submit”

## References

N/A

## Credit

Sharra Neely, she/her

### CODE REVIEW

**Review by sarken — COMMENTED** [review]
Thank you for the pull request! 

Some of our teams are currently reviewing the TOS and TOS FAQ, so we've been avoiding changes to those files for the time being. However, I'll check with them to see if we can make an exception for these changes. I'll let you know what they say when I hear back!

**Comment by sarken** [comment]
Hi, @sharra44! It look like our testers [found a few issues](https://otwarchive.atlassian.net/browse/AO3-6220?focusedCommentId=357822). Are you be available to fix those issues, or would you like someone else to take over?

**Comment by sharra44** [comment]
I can fix them!

**Comment by sarken** [comment]
Yay, thank you! (Just fyi, I edited your comment because I noticed GitHub's reply-by-email function inadvertently revealed some personal information.)

**Comment by sarken** [comment]
Hi again, @sharra44! Do you think you can have the fixes for this in the next few days? If not, that's fine, but we might need to hand it off to someone else in that case -- we're almost done testing the other issues in this release and will probably be deploying this weekend or early next week.

**Pull request merged**
