### PR TITLE
AO3-4368 Update gems

### PR DESCRIPTION
**Pull request by zz9pzza**
Resolves: https://otwarchive.atlassian.net/browse/AO3-4368

Updated New Relic. This caused updates to other interrelated gems.

### CODE REVIEW

**Comment by zz9pzza** [comment]
Just to be paranoid I would put this in its only tiny release.

**Comment by sarken** [comment]
This was marked ready to merge, but after the recent commits, it has errors in the importing tests that not the usual suspects.

**Comment by ariana-paris** [comment]
Looks as if the issues with this were fixed and it is now passing.

**Comment by zz9pzza** [comment]
Added label to ensure not merged

**Comment by sarken** [comment]
Took off the coder action label and added a new Deferred or Superseded label to more accurately reflect the status.

**Comment by sarken** [comment]
Is there a particular reason we're keeping this open?

**Pull request closed without merging**
