### PR TITLE
AO3-4446 Update unicorn and raindrops

### PR DESCRIPTION
**Pull request by zz9pzza**
https://otwarchive.atlassian.net/browse/AO3-4446

### CODE REVIEW

**Comment by sarken** [comment]
Could you supply some testing details to the issue for this, please? Even if it's just "test that you can access the Archive, because this changes the unicorns" or just... something so we know what this affects? Then we can mark it ready to merge.

**Comment by cesy** [comment]
raindrops is a real-time stats toolkit to show statistics for Rack HTTP servers. So basic test is that you can still access the site, and thorough test would be to check the status page for the servers.

**Comment by zz9pzza** [comment]
We don't provide the status page. The test for me would be can we access the archive and if I log in to the servers cna I convince myself that the right unicorn is being used as we do actually have unicorn installed in the general rvm pool so I would need to work out which one was being used.

**Comment by shalott** [comment]
Is there a reason to install raindrops and NOT to provide the status page? How would you work out which unicorn was being used?

**Comment by zz9pzza** [comment]
I think we need to use raindrops, we can see which unicorns are being used by looking at the haproxy status page.

**Comment by shalott** [comment]
james, I'm sorry, but this still doesn't give me anything to review. Can you answer these questions:

What do unicorn and raindrops do in our site roughly? 
Why are we doing this upgrade? (eg, security, performance improvements, just keeping up.)
What has changed in unicorn and raindrops?
What will visibly go wrong on the archive if this breaks? What should an end-user QA tester look for?  How can they confirm the upgrade is working? If a QA tester cannot do this please say so explicitly. 

Since you have said the strong test is to log in to the servers and convince yourself the right unicorn is being used can you explain how that is done? I am happy to do the test when it happens but I need more guidance on how. That is, how does someone who is NOT you look and see which unicorn is being used (where is the haproxy page and how do I access it?) What marks the "right" unicorn? What distinguishes the right from the wrong unicorn? 

More broadly, and I'm sorry for this tldr -- but I think these gem updates are really deceptive because the code change is so tiny. IMO, the actual work that has to go into these updates is research and explanation: finding out what the gem does and identifying where we use it (and if and where our tests exercise it), and then explaining the upgrade in sufficient detail that someone reviewing your work can feel confident that you have made the right call and that we understand what to look for. With a one line description and issue, we just have no way of assessing whether the research has been done and giving feedback on it. 

And if we DON'T do that research, then we're asking to break the site and have to revert which is a huge waste of time and energy, and I really don't think that is a risk we have to accept for every gem upgrade. There may be some gem upgrades where the changes in the gem have been so massive it would take a really long time to figure it out, but even then at least you could say "the gem is used for X and Y and it affects our code in these places."

**Comment by zz9pzza** [comment]
So one at a time:

What do unicorn and raindrops do in our site roughly? 

So the unicorns are the pre-forking web servers which sit behind rack they mean we have an efficient system sending the work to application.

Why are we doing this upgrade? (eg, security, performance improvements, just keeping up.)

In general we are doing the gem upgrades to make the work of getting to rails 4 easier as later version of gems have support for rails 4 and rails 5. There is the general trying to keep up to date and some gems do have security issues but that is not the case here.

What has changed in unicorn and raindrops?

This is the nearest to a release notes http://bogomips.org/unicorn.git/commit/?id=f8d431040eb863b226ded089113340e68d598914

In short if anything it will slow things down a tich.

What will visibly go wrong on the archive if this breaks?

There will be no web pages produced at all ( assuming unicorn fails completely )

What should an end-user QA tester look for? How can they confirm the upgrade is working? If a QA tester cannot do this please say so explicitly.

A QA person can not tell additionally as unicorn is installed as a gem for the ao3app user it really is harder.

Since you have said the strong test is to log in to the servers and convince yourself the right unicorn is being used can you explain how that is done? I am happy to do the test when it happens but I need more guidance on how. That is, how does someone who is NOT you look and see which unicorn is being used (where is the haproxy page and how do I access it?) What marks the "right" unicorn? What distinguishes the right from the wrong unicorn?

As ao3app on test-app01:

ao3app@test-app01:~$ ps -ef | grep ao3app |grep unicorn | head -2
ao3app   11645     1  0 17:00 ?        00:00:11 unicorn master -c /home/ao3app/conf//unicorn_i18n.rb -D                                                                                                                 
ao3app   11659 11645  0 17:00 ?        00:00:00 unicorn worker[0] -c /home/ao3app/conf//unicorn_i18n.rb -D          

ao3app@test-app01:/proc/11645/cwd$ cd /proc/11645/cwd
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /proc/11645/cwd/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

ao3app@test-app01:/proc/11645/cwd$ 
ao3app@test-app01:/proc/11645/cwd$ which unicorn
/home/ao3app/.rvm/gems/ruby-2.0.0-p643@global/bin/unicorn
ao3app@test-app01:/proc/11645/cwd$ unicorn -v
unicorn v4.6.3
compared to the "user version"
ao3app@test-app01:~$ unicorn -v
unicorn v4.9.0

So we are a long way behind, I have an expectation that speed between the old and the new are probably of the same order.

**Comment by zz9pzza** [comment]
More broadly, and I'm sorry for this tldr -- but I think these gem updates are really deceptive because the code change is so tiny. IMO, the actual work that has to go into these updates is research and explanation: finding out what the gem does and identifying where we use it (and if and where our tests exercise it), and then explaining the upgrade in sufficient detail that someone reviewing your work can feel confident that you have made the right call and that we understand what to look for. With a one line description and issue, we just have no way of assessing whether the research has been done and giving feedback on it.

And if we DON'T do that research, then we're asking to break the site and have to revert which is a huge waste of time and energy, and I really don't think that is a risk we have to accept for every gem upgrade. There may be some gem upgrades where the changes in the gem have been so massive it would take a really long time to figure it out, but even then at least you could say "the gem is used for X and Y and it affects our code in these places."

I do agree with you and to an extent I am relying on our test suites to pick up issues, we don't have the resources to do this properly. The test suite does pick up some issues and is providing minimal confidence however it is not all encompassing and things do run differently in test than in production/staging.

Depending on the gem I may have done more or less research but your right that is not being communicated. And it is really unclear what some of the gems are used for.

**Comment by zz9pzza** [comment]
( Ps this one is relatively low risk, unless the performance issues only turn up at scale. I could deploy it by hand on a single app server and see how it went ).

In fact maybe we should have a deploy process for that where we can put tiny minimal changes on to a single server and watch it.

**Comment by shalott** [comment]
I think in general some system of deploying changes to a small subset of production first would be great if we can swing it. In any case, I have been able to run the test specified and having read up on the changes I feel reasonably confident this one is safe to go. Thanks!

**Comment by sarken** [comment]
Alas, this has gone grey.

**Pull request closed without merging**
