### PR TITLE
AO3-4430 update best_in_place

### PR DESCRIPTION
**Pull request by zz9pzza**
https://otwarchive.atlassian.net/browse/AO3-4430

https://github.com/bernat/best_in_place

Comes from : https://github.com/otwcode/otwarchive/commit/bfb492dc93436839f969d998b40f339c60317104

I am guessing auto complete things to test ( I would also test the ajax kudos and comment bits just in case )

### CODE REVIEW

**Comment by sarken** [comment]
>Best in Place is a jQuery based AJAX Inplace-Editor that takes profit of RESTful server-side controllers to allow users to edit stuff with no need of forms. If the server has standard defined REST methods, particularly those to UPDATE your objects (HTTP PUT), then by adding the Javascript file to the application it allows all the fields with the proper defined classes to become user in-place editable.

We definitely don't do that anywhere, and I can't find best_in_place or bip buried anywhere in our code. We don't even load the JavaScript on the site. It _looks_ like it was added for tag sets, according to https://github.com/otwcode/otwarchive/commit/bfb492dc93436839f969d998b40f339c60317104, but I can't see anywhere it's currently being used. 

@shalott, do you happen to remember what this gem is for?

**Comment by shalott** [comment]
Hmm is it used in the tag set nominations? If it's not there then it's just outdated from when we were looking at doing more Ajaxy editing.

Naomi

**Comment by zz9pzza** [comment]
I can try and take it out of the Gemfile completely and if it passes the automated tests we can see :)

**Comment by sarken** [comment]
@elzj - Does the ready to merge label mean you know where we use this/can confirm it's used?

**Comment by sarken** [comment]
Just going to ping @elzj again with my question re: where this is used/how to test

**Pull request closed without merging**
