### PR TITLE
AO3-3952 Increase max characters allowed (but not number displayed)

### PR DESCRIPTION
**Pull request by sarken**
## Issue

https://otwarchive.atlassian.net/browse/AO3-3952

## Purpose

We want our various fields to allow more characters than we tell users, so folks who enter the maximum allowed don't run into issues once we start fiddling with their HTML. I used MAX * 1.02, since that was the formula we used on the field we'd already applied this to.

## Testing

Refer to JIRA

### CODE REVIEW

**Comment by sarken** [comment]
Marking Needs Coder Action due to merge conflicts.

**Comment by sarken** [comment]
Resolved merge conflicts due to recent maximum character increase on comments, if someone wants to recheck the values for comments.

**Comment by redsummernight** [comment]
> the merge conflicts will hit every time this branch is rebased against current master

 On a pull request branch, instead of rebasing, if you do [`git merge master`](https://github.com/otwcode/otwarchive/wiki/Commit-policy#commit-steps) you'll only have to resolve conflicts once.

> squashing the changes early

Once a pull request is open, I prefer adding new commits over squashing+force-pushing, because the latter way makes it hard to see what has changed since the last round of reviews. For the same reason, I avoid rebasing in favor of merging.

Before a pull request is open though, I'd squash/rebase as much as I want.

**Comment by gbhsrspm** [comment]
Ah, I can see the advantages to that; personally I use local diffs because I find github's interface pretty painful for code-review anyway (I like gh for _browsing_ code, but am a big gerrit fan, hahaha :)). (I'm used to systems that automatically merge code as-is from review, upon approval, where contributors rebase as they go so that the rebases themselves are reviewed. That way rebase-related errors can't get onto master. But yeah, depends on tooling and whatever the team's most comfortable with.)

**Comment by sarken** [comment]
Closing so I can get under 5 pull requests and open a new one for an issue that's blocking two of my existing PRs.

**Pull request closed without merging**
