### PR TITLE
AO3-1870 Add mass unassignment of fandoms in user wrangling page

### PR DESCRIPTION
**Pull request by hatal175**
## Issue

https://otwarchive.atlassian.net/browse/AO3-1870

## Purpose

Adding a mass unassignment option to user tag wrangling page.

## Testing

I've added a few lines to a feature test. Also I'd appreciate an opinion on how the interface change looks.

## Credit

Tal Hayon

Please use he.

### CODE REVIEW

**Comment by sarken** [comment]
Just adding a screenshot for reference 
unassign

**Comment by sarken** [comment]
Thanks for looking at this! I've spoken to the Tag Wrangling chairs, and they have a couple of requests: 

First, they'd like validation that makes it so only an admin or the wrangler who owns the page (i.e. testy if it's ao3.org/tag_wranglers/testy) can deassign fandoms.

Second, they'd like a confirmation step. For users with JavaScript enabled, that can be as simple as a confirmation dialogue asking, "Are you sure you want to deassign these fandoms?" For a non-JavaScript fallback, it should be something like the [confirmation page for deleting multiple works](https://github.com/otwcode/otwarchive/blob/master/app/views/works/confirm_delete_multiple.html.erb):

```
<!--Descriptive page name, messages and instructions-->
<h2 class="heading"><%= ts("Unassign Fandoms") %></h2>

<p class="caution">
  You are about to unassign the following fandoms from [wrangler's name]:
</p>

[list of fandoms]

  <ul class="actions">
    <li><%= submit_tag ts("Yes, Unassign Fandoms") %></li>
    <li><%= link_to ts("Cancel"), tag_wrangler_path(wrangler) %></li>
  </ul>

<% end %>
<!--/content-->
```

Would you be able to make these changes?

**Comment by hatal175** [comment]
I believe so.

**Comment by hatal175** [comment]
Does this limitation : "validation that makes it so only an admin or the wrangler who owns the page can deassign fandoms." apply to the wranglers page as well? Or should wranglers still be able to unassign fandoms from other wranglers from there?

**Comment by sarken** [comment]
Thanks for asking! The Tag Wrangling chairs say the limitation shouldn't apply to the wranglers page.

**Pull request closed without merging**
