### PR TITLE
AO3-6260 Remove setup files for Codeship tests

### PR DESCRIPTION
**Pull request by redsummernight**
## Issue

https://otwarchive.atlassian.net/browse/AO3-6260

## Purpose

Remove some unused files.

## Testing Instructions

None.

### CODE REVIEW

**Review by sarken — COMMENTED** [review]
Should we also take the Codeship build status badge off the README?

**Comment by redsummernight** [comment]
We should not because we're still using it for staging deploys.

**Comment by sarken** [comment]
Ah, so it'll let us know if the deploy to staging fails, not just the tests?

**Comment by redsummernight** [comment]
Yeah. Eventually I'd like to move away from Codeship for deploys as well ([AO3-6133](https://otwarchive.atlassian.net/browse/AO3-6133)), but for now we keep the badge.

**Pull request merged**
