### PR TITLE
AO3-4230 work blurb caching fix

### PR DESCRIPTION
**Pull request by zz9pzza**
Merge this after https://github.com/otwcode/otwarchive/pull/2390

https://otwarchive.atlassian.net/browse/AO3-4230

This should hopefully fix the blurb caching issues.

### CODE REVIEW

**Comment by sarken** [comment]
Psst -- you forgot to link to the issue in the PR comment

**Comment by zz9pzza** [comment]
Thanks I have done, that ( I will do a pull from zz9pzza:AO3-4512 when that gets ready to merge.

**Comment by shalott** [comment]
This needs tests too as per AO3-4512.

**Comment by shalott** [comment]
Got it! Looks good.

**Comment by zz9pzza** [comment]
@shalott This is based off https://github.com/otwcode/otwarchive/pull/2390 as I need to get the cache invalidation working. So it shouldn't be merged before that.

**Pull request merged**
