### PR TITLE
AO3-6152 Upgrade Rails to version 5.2.5

### PR DESCRIPTION
**Pull request by CristinaRO**
## Purpose

What does this PR do?

Upgrade Rails to version 5.2.5. There shouldn't be any breaking changes.

The purpose of this point release seems to be to update `marcel` to its first stable version, 1.0.0, which doesn't depend on `mimemagic`, a gem that has recently been involved in a licensing incident.

Our code still drags in `mimemagic` as a dependency of `paperclip`. This PR also updates `mimemagic` to its latest 0.3.x version, which is now properly MIT licensed. (All the previous 0.3.x versions have been yanked due to the aforementioned licensing incident.)

**The system on which the code runs will need to have a copy of `freedesktop.org.xml`, [per these instructions](https://github.com/mimemagicrb/mimemagic#dependencies)**

# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [ ] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6152

## Testing Instructions

How can the Archive's QA team verify that this is working as you intended?

Smoke test?

## References

Are there other relevant issues/pull requests/mailing list discussions?

## Credit

*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?*

Enigel

*What pronouns do you prefer (she/her, he/him, zie/hir etc)?*

she/her

### CODE REVIEW

**Review by redsummernight — APPROVED** [review]
paperclip is yet another thing we need to get rid of ([AO3-5578](https://otwarchive.atlassian.net/browse/AO3-5578)) but that's a problem for future us.

**Comment by redsummernight** [comment]
I confirmed that this will work in our development (Docker) as well as staging/production environments, as they have this package installed:
```
# apt list shared-mime-info
shared-mime-info/stable,now 1.10-1 amd64 [installed,automatic]
```
which provides the file `/usr/share/mime/packages/freedesktop.org.xml` [used by mimemagic](https://github.com/mimemagicrb/mimemagic/blob/22c06826417ed67c02b94ebc9998c24da5a03c56/ext/mimemagic/Rakefile#L10).

**Review by redsummernight — COMMENTED** [review]
One last thing, can you add shared-mime-info to the packages we install for Docker?

https://github.com/otwcode/otwarchive/blob/2ca46f1113662672fa367fd1789f2ac66a3ad7ee/config/docker/Dockerfile#L4-L11

**Comment by CristinaRO** [comment]
Thank you @redsummernight ! I've added a commit with the change to the Dockerfile.

**Pull request merged**
