### PR TITLE
AO3-4574 More minor gem updates

### PR DESCRIPTION
**Pull request by zz9pzza**
More small gem updates

https://otwarchive.atlassian.net/browse/AO3-4574

### CODE REVIEW

**Comment by sarken** [comment]
Please remember to include the issue link in the PR's comment (and update the issue status, if it hasn't been done automatically)

**Comment by sarken** [comment]
Actually... is this the right issue number? AO3-4457 says it's already been deployed.

**Comment by shalott** [comment]
This needs a new issue with information about what these changes affect so they can be tested properly. Are the changes all covered by automated testing? I think they all look pretty safe but would like some better idea before stamping.

**Comment by zz9pzza** [comment]
Created a new issue

https://otwarchive.atlassian.net/browse/AO3-4574

**Comment by zz9pzza** [comment]
Does this want a new review ?

**Comment by shalott** [comment]
Still looks fine to me!

**Pull request merged**
