### PR TITLE
AO3-4494 Omit time when showing date on which drafts will be deleted.

### PR DESCRIPTION
**Pull request by astirya**
https://otwarchive.atlassian.net/browse/AO3-4494

A few things:
1) I didn't know which format to use in declaring the helper functions (I prepended them with an underscore, but I can convert them into lambdas or whatever else.)
2) I didn't change the many references to time_in_zone, but I would like to make them uniformly datetime_in_zone in order to have parity with date_in_zone.  Thoughts?

### CODE REVIEW

**Comment by ariana-paris** [comment]
Yay, hitting the ground running :+1:
1. We don't currently have a naming convention for helper methods - they're sometimes defined in a private block, but as far as I've seen, always given a standard snake case name (could be a policy to review and encourage more privacy as I know the benefits of not leaking your internals all over the rest of the code, but that's the current status)

2. Unfortunately, the changes you've currently made seem to have broken any view that contains comments (the massive stack traces I saw on Travis appear to be comment-related). The Archive is a fragile old interconnected web in places so you'll probably need to run the tests locally and smoke-test the application manually to iterate over this and resolve those errors.

If the errors prove difficult to fix, it might be worth taking a more minimalistic approach and say, reformatting the date string in the controller that generates the message on the Drafts page to fix the immediate issue, and then work on a gradual upgrade of all instances of the time-related methods in a separate stage to unpick some more of the web. We can discuss the benefits of doing that further in chat anyway, because dates are a prickly problem in various ways and it would great to have someone tackle them!

**Comment by astirya** [comment]
Thanks for the feedback!  I was having trouble getting cucumber to run (for whatever reason, the test env appears to use the config.yaml rather than local.yaml), but it works now, and I'll make sure to run the unit tests from here on.

Question: do you guys have some way of running the hound checks outside of pushing?  This is my first foray into Ruby, so I know I'm going to end up having weird syntax.  I have a syntax checker I run in vim, but it isn't catching everything that Hound does.  I feel bad re-initiating the tests to fix whitespace over and over.

**Comment by zz9pzza** [comment]
I would look at rubocop ( https://github.com/bbatsov/rubocop ) 

gem install rubocop

I don't think it follows our hound config though but I think it is the same engine.

**Comment by astirya** [comment]
That is exactly what I ended up doing; it turns out that Hound uses rubocop under the hood, so I just am using the archive's .rubocop.yml.

**Comment by sarken** [comment]
Just checking -- is this ready for re-review? If so, we'll switch the label over to "Coder has actioned review" so we know to give it another look.

**Comment by astirya** [comment]
I need to write tests, still, but it's functional!

**Comment by sarken** [comment]
Okay, thanks! We'll leave the label as-is for now and change it when the tests are ready.

**Comment by sarken** [comment]
Thanks for the updates, @astirya! I've switched the label.

**Comment by astirya** [comment]
Thanks, @sarken!  I wasn't sure whether to update the labels myself.  Please let me know if you want me to add more tests!  I mostly just updated existing tests to check for a time/date, but it should be easier to alter it than it was to add it.

**Comment by sarken** [comment]
Oh, yes, please do change the labels in the future! (We actually weren't entirely sure if that power was only for team members, so thanks for clearing that up! I will adjust the documentation accordingly.)

I'll defer to @ariana-paris on the test coverage, since she was the initial reviewer.

**Pull request merged**
