### PR TITLE
AO3-6375 Comments stay in inbox after being hidden by admin or marked as spam

### PR DESCRIPTION
**Pull request by ceithir**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)?
* [x] Do you have fewer than 5 pull requests already open?

## Issue

https://otwarchive.atlassian.net/browse/AO3-6375

## Purpose

Hide spam/hidden by admin comments from inbox.

## Testing Instructions

As per the "Steps to reproduce" of the JIRA issue.

## Credit

Ceithir (he/him)

### CODE REVIEW

**Comment by sarken** [comment]
Hi, Ceithir!

Thank you so much for this pull request. I know you've contributed before, but I'm having some trouble finding you in Jira. Do you have an account we can assign the issue to? 

If not, you're welcome to make one so you can claim, comment on, and transition issues in the future. (It makes things a bit easier for us on the organizational side if the Full Name on your Jira account either closely matches the name you'd like us to credit in the release notes or includes it in parentheses, e.g. "Nickname (PREFERRED NAME).")

**Comment by ceithir** [comment]
Sorry, indeed forgot to join the JIRA last time. Should now be fixed.

**Comment by ceithir** [comment]
`features/comments_and_kudos/hidden_comments.feature` appears to be only passing intermittently on master, at least on my machine. Not sure why.

**Comment by sarken** [comment]
No worries! Your Jira account should be all set up with the proper permissions now.

Usually when we have intermittent failures, it's because the test needs a brief pause like in #4316. (That test is pretty new, so we haven't noticed it being flaky before.)

**Review by sarken — APPROVED** [review]

**Pull request merged**
