### PR TITLE
AO3-5426 Removed unused link_to_tag_with_count method from pseuds_helper

### PR DESCRIPTION
**Pull request by melinath**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [ ] Have you added tests for any changed functionality?
  ^ N/A
* [x] Have you added the [JIRA](https://otwarchive.atlassian.net) issue number as the *first* thing in your pull request title (eg: `AO3-1234 Fix thing`)
* [x] Have you updated or commented on the JIRA issue with the information below?

## Issue

https://otwarchive.atlassian.net/browse/AO3-5426

## Purpose

This PR removes the unused link_to_tag_with_count method from pseuds_helper.

## Testing Instructions

N/A - no functional changes.

## Credit

*What name do you want us to use to credit your work in the [Archive of Our Own's Release Notes](https://archiveofourown.org/admin_posts?tag=1)?*

Stephen Burrows

*What pronouns do you prefer (she/her, he/him, zie/hir etc)?*

he/him

### CODE REVIEW

**Comment by sarken** [comment]
Thank you for the pull requests -- we appreciate your enthusiasm! However, we have a pretty full schedule for the next several months and we don't anticipate having much opportunity to deploy many grab bags of small issues.

To avoid having too many pull requests piling up -- it's happened to us before; we've only just started to put a dent in the pile after a few years of hard work -- we'd appreciate it if you could hold off on opening any more for the time being.

You can leave all of the current ones open, but ideally we'd like to stay in the range of 3-5 open pull requests per contributor. It helps us keep from getting swamped with pull requests that have developed merge conflicts after big changes like Rails or Ruby updates or refactoring of existing features.

Thank you for understanding!

**Comment by melinath** [comment]
yep, I totally understand :-) Thanks!

**Comment by melinath** [comment]
The one thing is that I'm currently unemployed due to COVID so I have more time on my hands than I (hopefully) will in a few months; I am happy to hold off on contributing for now, but if there's any way I can take advantage of this time that would be more useful to you, I am happy to do that as well.

**Comment by sarken** [comment]
I'm sorry to hear that!

A few of us discussed what might be of the most help, and would you be interested in working on [AO3-5907: Generate sharing options when the user pushes the "Share" button, not when the work page is loaded](https://otwarchive.atlassian.net/browse/AO3-5907)? It would help reduce load and improve privacy, so we'd definitely be able to prioritize it once it was complete.

**Comment by melinath** [comment]
yes, absolutely! Thanks :-)

**Pull request merged**
