### PR TITLE
AO3-6321 Text changes to TOS FAQ-FNOK section

### PR DESCRIPTION
**Pull request by tararosenthal**
# Pull Request Checklist

* [x] Have you read ["How to write the perfect pull request"](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [x] Have you read the [contributing guidelines](https://github.com/otwcode/otwarchive/blob/master/CONTRIBUTING.md)?
* [x] Have you added [tests for any changed functionality](https://github.com/otwcode/otwarchive/wiki/Automated-Testing)?
* [x] Have you added the [Jira](https://otwarchive.atlassian.net) issue number
  as the *first* thing in your pull request title (e.g. `AO3-1234 Fix thing`)
* [x] Do you have fewer than 5 pull requests already open? If not, please wait
  until they are reviewed and merged before creating new pull requests.

## Issue

https://otwarchive.atlassian.net/browse/AO3-6321

## Purpose

Changes the text and links to direct fannish next-of-kin concerns to the support team rather than the abuse team using translation-friendly syntax.

## Testing Instructions

Check that text and links are as indicated in the Jira issue.

## References

Blocked by https://otwarchive.atlassian.net/browse/AO3-6317

## Credit

Tara Rosenthal (she/her)

### CODE REVIEW

**Comment by sarken** [comment]
Hi, Tara! Thanks for working on this. However, due to the [ongoing harassment of our volunteers](https://archiveofourown.org/admin_posts/22557), it will be a while before we make the admin permissions change that's blocking this. So I'm going to close this for now so it doesn't count against your pull request total.

**Comment by tararosenthal** [comment]
I'm so sorry to hear that this is still going on. It's understandable that you would delay this change. Thank you for letting me know.

**Comment by brianjaustin** [comment]
@tararosenthal your changes look good to me! When you have a chance, could you take a pass at the merge conflicts? Once those are sorted I can approve

**Comment by sarken** [comment]
Merge conflicts resolved in #4629, so I'm going to close this. Thanks for working on it!

**Pull request closed without merging**
